name: Test Laravel App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    name: Run PHPUnit and Pest tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: [8.2, 8.3]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, pdo, mysql, xml, curl, exif, bcmath, gd, imagick, intl, zip

    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest

    - name: Set up Laravel environment
      run: php artisan key:generate --ansi

    - name: Run database migrations
      run: php artisan migrate --env=testing --force

    - name: Run PHPUnit tests
      run: vendor/bin/phpunit

    - name: Run Pest tests
      run: vendor/bin/pest --coverage

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/
